### PR TITLE
use globals if avialable

### PR DESCRIPTION
**Pull request by calvinmetcalf**
not sure how to test this as this is being set once on module load, do I have access to the resolver inside the test module ?

### CODE REVIEW

**Comment by stefanpenner** [comment]
> user globals if avialable

just double checking, you meant `use` not `user` right?

> do I have access to the resolver inside the test module ?

sorry, I don't quite understand

**Comment by calvinmetcalf** [comment]
- yes typo
- so the way I'd go about testing this especially in phantom, would be I'd put a fake fetch object on window an see if it was what I got when I imported fetch, but you can't do that with ES6 module syntax as they will always load before the current module is run so my guess as to the best way to test this would be to access the module resolver somehow...

**Comment by stefanpenner** [comment]
So one approach, would be to change: https://github.com/stefanpenner/ember-fetch/blob/master/assets/module-template.js.t#L5-L13 to instead use `defineProperty` so access to self.Header is always actually being fetched from global.Header

This would allow patching during tests, and likely more resilient to other related polyfils being added.

**Comment by calvinmetcalf** [comment]
I though the whole point of this was so it wouldn't pollute global scope?

**Comment by stefanpenner** [comment]
I think that continues to be true. I can take a closer look after lunch

**Comment by calvinmetcalf** [comment]
In which case I may be confusing what you meant, one idea could be to to not export the self object that the shim binds too but to put getters on the export object which dynamically grabs global.fetch/Request/whatever or the shim one.

**Pull request closed without merging**
